name: CI (master)

run-name: ${{ github.run_id }}.${{ github.run_attempt }} ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: ci-master
  cancel-in-progress: false

jobs:
  setup:
    runs-on: self-hosted
    outputs:
      db_host: "172.30.1.10"
      db_name: sestio_usuarios
      vault_url: ${{ steps.load-urls.outputs.vault_url_dev }}
      docker_registry: ${{ steps.load-urls.outputs.docker_registry }}
      nuget_url: ${{ steps.load-urls.outputs.nuget_url }}
    steps:
    - name: Load URLs
      id: load-urls
      uses: sestio/gh/actions/load-urls@master

  build:
    needs: [setup]
    uses: ./.github/workflows/reuse-build.yaml
    with:
      tags: |
        master
        master-ci.${{ github.sha }}.${{ github.run_attempt }}
      docker_registry: ${{ needs.setup.outputs.docker_registry }}
      nuget_url: ${{ needs.setup.outputs.nuget_url }}
    secrets: inherit

  test:
    needs: [setup, build]
    uses: ./.github/workflows/reuse-test.yaml
    with:
      docker_registry: ${{ needs.setup.outputs.docker_registry }}
      image: ${{ needs.build.outputs.testrunner_image }}
    secrets: inherit

  db:
    needs: [setup, build, test]
    uses: ./.github/workflows/reuse-db.yaml
    with:
      db_host: ${{ needs.setup.outputs.db_host }}
      db_port: ${{ needs.setup.outputs.db_port }}
      db_name: ${{ needs.setup.outputs.db_name }}
      vault_url: ${{ needs.setup.outputs.vault_url }}
      docker_registry: ${{ needs.setup.outputs.docker_registry }}
      image: ${{ needs.build.outputs.migrationrunner_image }}
    secrets: inherit

  deploy_dev:
    runs-on: self-hosted
    needs: [setup, build, db]
    container: alpine/helm:3.10.2
    steps:
    - uses: sestio/gh/actions/helm-deploy@master
      env:
        REPO_USERNAME: ${{ secrets.HELM_USERNAME }}
        REPO_PASSWORD: ${{ secrets.HELM_PASSWORD }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        release: api-usuarios
        namespace: sestio-dev
        chart-name: api-usuarios
        chart-version: 0.1.1
        values: |
          replicaCount: "2"
          image:
            image: ${{ needs.build.outputs.runtime_image }}
          ingress:
            enabled: "true"
            host: "sestio-dev.local.vmrlab.net"
          app:
            logLevels:
              Default: "Information"
              Microsoft.AspNetCore: "Information"
          db:
            connectionTpl: "Database=${{ needs.setup.outputs.db_name }};
                            Host=${{ needs.setup.outputs.db_host }};
                            Username={#username#};
                            Password={#password#}"
            enableDetailedErrors: "true"
            enableSensitiveDataLogging: "true"
          vault:
            enabled: "true"
            role: "sestio-dev"
            debugLevel: "debug"
            secrets:
              db: "sestio-dev-postgres/creds/sestio-usuarios"
