name: CI (master)

run-name: ${{ github.run_id }}.${{ github.run_attempt }} ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: ci-master
  cancel-in-progress: false

env:
  DB_HOST: "172.30.1.10"
  DB_NAME: sestio_usuarios

jobs:
  build:
    uses: ./.github/workflows/reuse-build.yaml
    with:
      tags: |
        master
        master-ci.${{ github.sha }}.${{ github.run_attempt }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      nuget_url: ${{ vars.NUGET_URL }}
    secrets: inherit

  test:
    needs: [build]
    uses: ./.github/workflows/reuse-test.yaml
    with:
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      image: ${{ needs.build.outputs.testrunner_image }}
    secrets: inherit

  db:
    needs: [build, test]
    uses: ./.github/workflows/reuse-db.yaml
    with:
      db_host: ${{ env.DB_HOST }}
      db_name: ${{ env.DB_NAME }}
      vault_url: ${{ vars.VAULT_URL }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      image: ${{ needs.build.outputs.migrationrunner_image }}
    secrets: inherit

  deploy_dev:
    runs-on: self-hosted
    needs: [build, db]
    container: alpine/helm:3.10.2
    steps:
    - uses: sestio/gh/actions/helm-deploy@master
      env:
        REPO_USERNAME: ${{ secrets.HELM_USERNAME }}
        REPO_PASSWORD: ${{ secrets.HELM_PASSWORD }}
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
        release: api-usuarios
        namespace: sestio-dev
        chart-name: api-usuarios
        chart-version: 0.1.2
        values: |
          replicaCount: "2"
          image:
            image: ${{ needs.build.outputs.runtime_image }}
          ingress:
            enabled: "true"
            host: "sestio-dev.local.vmrlab.net"
          app:
            logLevels:
              Default: "Information"
              Microsoft.AspNetCore: "Information"
            minutosDuracaoSessao: 60
            minutosDuracaoAccessToken: 5
          db:
            connectionTpl: "Database=${{ env.DB_NAME }};
                            Host=${{ env.DB_HOST }};
                            Username={#username#};
                            Password={#password#}"
            enableDetailedErrors: "true"
            enableSensitiveDataLogging: "true"
          vault:
            enabled: "true"
            role: "sestio-dev"
            debugLevel: "debug"
            secrets:
              globals: "sestio-dev-kv/globals"
              db: "sestio-dev-postgres/creds/sestio-usuarios"
