name: CI (master)

run-name: ${{ github.run_id }}.${{ github.run_attempt }} ${{ github.event.head_commit.message }}

on:
  workflow_dispatch:
  push:
    branches: [master]

concurrency:
  group: ci-master
  cancel-in-progress: false

jobs:
  build:
    uses: ./.github/workflows/reuse-build.yaml
    with:
      tags: |
        master
        master-ci.${{ github.sha }}
    secrets: inherit

  test:
    needs: [build]
    uses: ./.github/workflows/reuse-test.yaml
    with:
      image: ${{ needs.build.outputs.testrunner-image }}
    secrets: inherit

  deploy:
    runs-on: self-hosted
    needs: [build, test]
    environment: development
    steps:
    - name: Docker login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - uses: sestio/gh/actions/db-migrate@master
      with:
        image: ${{ needs.build.outputs.migrationrunner-image }}
        vault-url: ${{ vars.VAULT_URL_DEV }}
        vault-token: ${{ secrets.VAULT_TOKEN }}
        vault-secret: ${{ vars.VAULTSECRET_DBMIGRATION }}
        connection: |
          Database=${{ vars.DB_NAME }};
          Host=${{ vars.DB_HOST }};
          Username={#username#};
          Password={#password#}
    - uses: sestio/gh/actions/helm-deploy@master
      with:
        release: ${{ vars.DEPLOY_RELEASENAME }}
        namespace: ${{ vars.DEPLOY_NAMESPACE }}
        repo-url: ${{ vars.HELM_URL }}
        repo-username: ${{ secrets.HELM_USERNAME }}
        repo-password: ${{ secrets.HELM_PASSWORD }}
        kube-config: ${{ secrets.KUBE_CONFIG }}
        chart-name: ${{ vars.DEPLOY_CHARTNAME }}
        chart-version: ${{ vars.DEPLOY_CHARTVERSION }}
        values: |
          replicaCount: ${{ vars.DEPLOY_REPLICACOUNT }}
          image:
            image: ${{ needs.build.outputs.runtime-image }}
          ingress:
            enabled: true
            host: ${{ vars.SESTIO_HOST_DEV }}
          app:
            logLevels:
              Default: Information
              Microsoft.AspNetCore: Information
            minutosDuracaoSessao: ${{ vars.APPVAR_MINUTOS_DURACAO_SESSAO }}
            minutosDuracaoAccessToken: ${{ vars.APPVAR_MINUTOS_DURACAO_ACESSSTOKEN }}
          db:
            connectionTpl: "Database=${{ vars.DB_NAME }};
                            Host=${{ vars.DB_HOST }};
                            Username={#username#};
                            Password={#password#}"
            enableDetailedErrors: true
            enableSensitiveDataLogging: true
          vault:
            enabled: true
            role: ${{ vars.VAULT_ROLE }}
            debugLevel: debug
            secrets:
              globals: ${{ vars.VAULTSECRET_GLOBALS }}
              db: ${{ vars.VAULTSECRET_DBCREDS }}
