name: CI (pull request)

run-name: ${{ github.run_id }}.${{ github.run_attempt }} ${{ github.event.pull_request.title }}

on:
  workflow_dispatch:
  pull_request:
    branches: [master]

concurrency:
  group: ci-pr-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/reuse-build.yaml
    with:
      tags: |
        tmp-pr-${{ github.run_id }}.${{ github.run_attempt }}
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      nuget_url: ${{ vars.NUGET_URL }}
      build_runtime: false
      build_migrationrunner: false
    secrets: inherit

  test:
    needs: [build]
    uses: ./.github/workflows/reuse-test.yaml
    with:
      docker_registry: ${{ vars.DOCKER_REGISTRY }}
      image: ${{ needs.build.outputs.testrunner_image }}
    secrets: inherit

