name: '[Reusable] Build'

on:
  workflow_call:
    inputs:
      tags:
        type: string
        required: true
      build-migrationrunner:
        type: boolean
        default: true
      build-testrunner:
        type: boolean
        default: true
      build-runtime:
        type: boolean
        default: true
    outputs:
      runtime-image:
        value: ${{ jobs.images.outputs.runtime-image }}
      testrunner-image:
        value: ${{ jobs.images.outputs.testrunner-image }}
      migrationrunner-image:
        value: ${{ jobs.images.outputs.migrationrunner-image }}

jobs:
  images:
    runs-on: self-hosted
    outputs:
      runtime-image: ${{ steps.build-images.outputs.runtime-image }}
      testrunner-image: ${{ steps.build-images.outputs.testrunner-image }}
      migrationrunner-image: ${{ steps.build-images.outputs.migrationrunner-image }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Docker login
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ vars.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build images
      id: build-images
      uses: sestio/gh/actions/build-images@master
      with:
        image-id: sestio/api-usuarios
        tags: ${{ inputs.tags }}
        docker-registry: ${{ vars.DOCKER_REGISTRY }}
        nuget-url: ${{ vars.NUGET_URL }}
        nuget-username: ${{ secrets.NUGET_USER }}
        nuget-password: ${{ secrets.NUGET_TOKEN }}
        build-migrationrunner: ${{ inputs.build-migrationrunner }}
        build-testrunner: ${{ inputs.build-testrunner }}
        build-runtime: ${{ inputs.build-runtime }}
